language: php
php:
  - 5.4
  - 5.3

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script:  
  - phpunit Heap/HeapTest.php
  - phpunit Queue/QueueTest.php
  